# Theme settings
name: OWASP CycloneDX
description: OWASP CycloneDX is a lightweight software bill of materials (SBOM) standard designed for use in application security contexts and supply chain component analysis.
doks:
    baseurl:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Use Cases
              item_url: '/use-cases'
            - item_name: Tool Center
              item_url: '/tool-center'
            - item_name: Specification
              item_url: 'https://cyclonedx.org/docs/1.2'
    footer:
        content:
            logo:
                text:
                image: true
            copyright:
        social_list:
            - network_name: twitter
              network_title: Twitter
              profile_url: 'https://twitter.com/CycloneDX_Spec'
            - network_name: github
              network_title: GitHub
              profile_url: 'https://github.com/CycloneDX'
            - network_name: groupsio
              network_title: Groups.io
              profile_url: 'https://groups.io/g/CycloneDX'
            - network_name: slack
              network_title: Slack
              profile_url: 'https://cyclonedx.org/slack/invite'
            - network_name: owasp
              network_title: OWASP
              profile_url: 'https://owasp.org/cyclonedx'
    google_analytics:
        tracking_code: G-PGCR5YBFQP
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./theme/_layouts
includes_dir: ./theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
include: [ '_redirects', '.well-known' ]
#permalink: /:title/
permalink: /news/:title/
url: "https://cyclonedx.org"
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-redirect-from
defaults:
  -
    scope:
      path:            "google*.html"
    values:
      sitemap:         false
